// Auto-generated by scripts/generate-build-info.js
// DO NOT EDIT MANUALLY

export const BUILD_INFO = {
  "version": "26.3.0",
  "buildDate": "2026-03-03T19:30:03.542Z",
  "buildTimestamp": 1772566203542,
  "displayDate": "03.03.2026",
  "displayTime": "22:30 GMT+3",
  "gitSha": "dev",
  "isProduction": false
} as const;

export type BuildInfo = typeof BUILD_INFO;
